name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-plan.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout PR Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: github-actions-terraform-plan
        aws-region: us-east-1

    - name: Get secrets from AWS Secrets Manager
      id: get-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with: 
        secret-ids: ${{ secrets.SECRETS_MANAGER_ARN }}
        parse-json-secrets: true

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.7
        terraform_wrapper: false

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Debug Terraform variables
      run: |
        echo "TF_VAR_mongodb_atlas_public_key: $MONGODB_ATLAS_PUBLIC_KEY"
        echo "TF_VAR_mongodb_atlas_private_key: $MONGODB_ATLAS_PRIVATE_KEY"
      env:
        MONGODB_ATLAS_PUBLIC_KEY: ${{ env.MONGODB_ATLAS_PUBLIC_KEY }}
        MONGODB_ATLAS_PRIVATE_KEY: ${{ env.MONGODB_ATLAS_PRIVATE_KEY }}

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      env:
        TF_VAR_mongodb_atlas_public_key: ${{ env.MONGODB_ATLAS_PUBLIC_KEY }}
        TF_VAR_mongodb_atlas_private_key: ${{ env.MONGODB_ATLAS_PRIVATE_KEY }}
        TF_VAR_mongodb_atlas_org_id: ${{ env.MONGODB_ATLAS_ORG_ID }}
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: ${{ steps.plan.outputs.stdout }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌`${{ steps.fmt.outcome }}`
          #### Terraform Initialization ⚙️`${{ steps.init.outcome }}`
          #### Terraform Validation 🤖`${{ steps.validate.outcome }}`
          #### Terraform Plan 📖`${{ steps.plan.outcome }}`

          <details><summary>Show Plan</summary>

          ```terraform
          ${process.env.PLAN}
          ```

          </details>

          *Pushed by: @${{ github.actor }}, Action: `${{ github.event_name }}`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Security Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
