name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/terraform-plan.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout PR Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: github-actions-terraform-plan
        aws-region: us-east-1

    - name: Get secrets from AWS Secrets Manager
      id: get-secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with: 
        secret-id: ${{ secrets.SECRETS_MANAGER_ARN }}
        parse-json-secrets: true

    - name: Debug secrets
      run: |
        echo "::add-mask::${{ steps.get-secrets.outputs.MONGODB_ATLAS_PUBLIC_KEY }}"
        echo "::add-mask::${{ steps.get-secrets.outputs.MONGODB_ATLAS_PRIVATE_KEY }}"
        echo "MONGODB_ATLAS_PUBLIC_KEY: ${{ steps.get-secrets.outputs.MONGODB_ATLAS_PUBLIC_KEY }}"
        echo "MONGODB_ATLAS_PRIVATE_KEY: ${{ steps.get-secrets.outputs.MONGODB_ATLAS_PRIVATE_KEY }}"